"""update-code

Revision ID: 2ac7eb1abd46
Revises: 52a2686f8225
Create Date: 2025-11-30 18:43:11.598200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac7eb1abd46'
down_revision: Union[str, None] = '52a2686f8225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('token', sa.String(length=5), nullable=True))
    op.create_index(op.f('ix_customer_token'), 'customer', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_token'), table_name='customer')
    op.drop_column('customer', 'token')
    # ### end Alembic commands ###
