"""first1

Revision ID: 52a2686f8225
Revises: 
Create Date: 2025-11-29 19:23:43.223373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52a2686f8225'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bakery',
    sa.Column('bakery_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('location', sa.Unicode(length=255), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('baking_time_s', sa.Integer(), nullable=False),
    sa.Column('timeout_sec', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('bakery_id')
    )
    op.create_table('bread_type',
    sa.Column('bread_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bread_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_detail',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('admin',
    sa.Column('admin_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_detail.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('bakery_bread',
    sa.Column('bakery_id', sa.Integer(), nullable=False),
    sa.Column('bread_type_id', sa.Integer(), nullable=False),
    sa.Column('preparation_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.bakery_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bread_type_id'], ['bread_type.bread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bakery_id', 'bread_type_id')
    )
    op.create_table('bread_cook_time_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bakery_id', sa.Integer(), nullable=True),
    sa.Column('new_avreage_cook_time', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.bakery_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('bakery_id', sa.Integer(), nullable=True),
    sa.Column('is_in_queue', sa.Boolean(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.bakery_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('queue_state_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bakery_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('state_json', sa.Unicode(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.bakery_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bakery_upcoming_bread',
    sa.Column('bakery_id', sa.Integer(), nullable=False),
    sa.Column('bread_type_id', sa.Integer(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id', 'bread_type_id'], ['bakery_bread.bakery_id', 'bakery_bread.bread_type_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.bakery_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['bread_type_id'], ['bread_type.bread_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bakery_id', 'bread_type_id')
    )
    op.create_table('bread',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('enter_date', sa.DateTime(), nullable=True),
    sa.Column('baked_at', sa.DateTime(), nullable=False),
    sa.Column('belongs_to', sa.Integer(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=True),
    sa.Column('bakery_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bakery_id'], ['bakery.bakery_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['belongs_to'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_bread',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('bread_type_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bread_type_id'], ['bread_type.bread_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'bread_type_id')
    )
    op.create_table('upcoming_customer',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    op.create_table('user_customer',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_detail.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'customer_id')
    )
    op.create_table('wait_list',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('is_in_queue', sa.Boolean(), nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wait_list')
    op.drop_table('user_customer')
    op.drop_table('upcoming_customer')
    op.drop_table('customer_bread')
    op.drop_table('bread')
    op.drop_table('bakery_upcoming_bread')
    op.drop_table('queue_state_snapshot')
    op.drop_table('customer')
    op.drop_table('bread_cook_time_log')
    op.drop_table('bakery_bread')
    op.drop_table('admin')
    op.drop_table('user_detail')
    op.drop_table('bread_type')
    op.drop_table('bakery')
    # ### end Alembic commands ###
